### ISSUE TITLE
Cannot get 'last_insert_id’ and the select with datetime failed

### ISSUE THREAD

**Issue by gusvny** [rbatis/rbatis#322]
Hi,

The behavior is very strange to me so I created a minimal codebase to reproduce the issues. I am using postgres 15 on window11, rustc 1.65.0 (897e37553 2022-11-02), here is my code base: https://github.com/gusvny/rbatis_test

the sample table DDL:
```
CREATE TABLE sere.todo_entry (
	id serial primary key,
	cont varchar NOT NULL,
	status varchar NOT NULL,
	deadline timestamp NULL,
	ctime timestamp NOT NULL,
	mtime timestamp NOT NULL,
);
```

It is a very simple case, the problems are: 

1. the last_insert_id is always None after the execution of a successful insert.
```
2022-11-17 17:35:25.5403117 INFO rbatis::plugin::log - [rbatis] [435855821017059328] Exec   ==> insert into todo_entry (cont,status,deadline,ctime,mtime) VALUES (?,?,?,?,?)
                                                      [rbatis]                      Args   ==> ["test","Pending",DateTime("2022-11-18 01:35:25.3513564"),DateTime("2022-11-18 01:35:25.3513716"),DateTime("2022-11-18 01:35:25.3513721")]
insert result: ExecResult { rows_affected: 1, last_insert_id: Null }
```

2. For select statement, the datatime field parse always failed:
```
2022-11-17 16:20:15.78986 INFO rbatis::plugin::log - [rbatis] [435836905750401024] Fetch  ==> select * from todo_entry where status = ?
                                                      [rbatis]                      Args   ==> ["Pending"]
thread 'tokio-runtime-worker' panicked at 'overflow when adding duration to instant', library\std\src\time.rs:584:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::panicking::panic_display<str>
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:72
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:56
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\option.rs:1880
   5: core::option::Option::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\option.rs:738
   6: std::time::impl$8::add
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\time.rs:585
   7: fastdate::datetime::DateTime::add
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\fastdate-0.1.30\src\datetime.rs:75
   8: fastdate::datetime::impl$1::add
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\fastdate-0.1.30\src\datetime.rs:319
   9: rbdc_pg::types::timestamp::impl$1::decode
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbdc-pg-0.1.19\src\types\timestamp.rs:34
  10: rbdc_pg::types::value::impl$1::decode
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbdc-pg-0.1.19\src\types\value.rs:256
  11: rbdc_pg::row::impl$2::get
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbdc-pg-0.1.19\src\row.rs:71
  12: rbdc::db::Connection::get_values::async_block$0<deadpool::managed::Object<rbdc::pool::pool::ManagerPorxy> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbdc-0.1.22\src\db.rs:68
  13: core::future::from_generator::impl$1::poll<enum2$<rbdc::db::Connection::get_values::async_block_env$0<deadpool::managed::Object<rbdc::pool::pool::ManagerPorxy> > > >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  14: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<alloc::vec::Vec<enum2$<rbs::value::Value>,alloc::alloc::Global>,enum2$<rbdc::error::Error> > > > >,core::marker::Send>,alloc::
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  15: rbatis::executor::impl$3::fetch::async_block$0
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.42\src\executor.rs:152
  16: core::future::from_generator::impl$1::poll<enum2$<rbatis::executor::impl$3::fetch::async_block_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  17: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  18: rbatis::executor::impl$2::fetch::async_fn$0
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.42\src\executor.rs:57
  19: core::future::from_generator::impl$1::poll<enum2$<rbatis::executor::impl$2::fetch::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  20: rbatis::executor::impl$22::fetch::async_block$0
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\rbatis-4.0.42\src\executor.rs:526
  21: core::future::from_generator::impl$1::poll<enum2$<rbatis::executor::impl$22::fetch::async_block_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  22: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<enum2$<rbs::value::Value>,enum2$<rbdc::error::Error> > > > >,core::marker::Send>,alloc::alloc::Global> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  23: serenitatis::service::todo_service::select_by_status::async_fn$0
             at .\src\service\todo_service.rs:74
  24: core::future::from_generator::impl$1::poll<enum2$<serenitatis::service::todo_service::select_by_status::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  25: serenitatis::service::todo_service::impl$3::list_todo::async_fn$0
             at .\src\service\todo_service.rs:111
  26: core::future::from_generator::impl$1::poll<enum2$<serenitatis::service::todo_service::impl$3::list_todo::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  27: serenitatis::controller::todo_ctl::list_todo::async_fn$0
             at .\src\controller\todo_ctl.rs:23
  28: core::future::from_generator::impl$1::poll<enum2$<serenitatis::controller::todo_ctl::list_todo::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  29: axum::handler::impl$0::call::async_block$0<core::future::from_generator::GenFuture<enum2$<serenitatis::controller::todo_ctl::list_todo::async_fn_env$0> > (*)(),core::future::from_generator::GenFuture<enum2$<serenitatis::controller::todo_ctl::list_todo::as
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.6.0-rc.4\src\handler\mod.rs:169
  30: core::future::from_generator::impl$1::poll<enum2$<axum::handler::impl$0::call::async_block_env$0<core::future::from_generator::GenFuture<enum2$<serenitatis::controller::todo_ctl::list_todo::async_fn_env$0> > (*)(),core::future::from_generator::GenFuture<e
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
  31: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> > > >,core::marker::Send>,alloc::all
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  32: futures_util::future::future::map::impl$2::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> > > >,co
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\future\future\map.rs:55
  33: futures_util::future::future::impl$15::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> > > >,core::
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\lib.rs:91
  34: axum::handler::future::impl$4::poll<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> > > >,core::marker::
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.6.0-rc.4\src\macros.rs:42
  35: futures_core::future::impl$2::try_poll<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,a
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.25\src\future.rs:82
  36: futures_util::future::try_future::into_future::impl$2::poll<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\future\try_future\into_future.rs:34
  37: futures_util::future::future::map::impl$2::poll<futures_util::future::try_future::into_future::IntoFuture<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<ht
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\future\future\map.rs:55
  38: futures_util::future::future::impl$15::poll<futures_util::future::try_future::into_future::IntoFuture<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_b
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\lib.rs:91
  39: futures_util::future::try_future::impl$56::poll<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\lib.rs:91
  40: tower::util::map_response::impl$10::poll<axum::handler::future::IntoServiceFuture<core::pin::Pin<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tower-0.4.13\src\macros.rs:38
  41: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >,enum2$
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  42: tower::util::oneshot::impl$3::poll<tower::util::boxed_clone::BoxCloneService<http::request::Request<hyper::body::body::Body>,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >,enum2$<cor
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tower-0.4.13\src\util\oneshot.rs:97
  43: axum::routing::route::impl$5::poll<hyper::body::body::Body,enum2$<core::convert::Infallible> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.6.0-rc.4\src\routing\route.rs:144
  44: futures_core::future::impl$2::try_poll<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> >,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >,en
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.25\src\future.rs:82
  45: futures_util::future::try_future::into_future::impl$2::poll<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> > >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\future\try_future\into_future.rs:34
  46: futures_util::future::future::map::impl$2::poll<futures_util::future::try_future::into_future::IntoFuture<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> > >,futures_util::fns::MapOkFn<http::response::Response<h
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\future\future\map.rs:55
  47: futures_util::future::future::impl$15::poll<futures_util::future::try_future::into_future::IntoFuture<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> > >,futures_util::fns::MapOkFn<http::response::Response<http_
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\lib.rs:91
  48: futures_util::future::try_future::impl$56::poll<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> >,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Er
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.25\src\lib.rs:91
  49: tower::util::map_response::impl$10::poll<axum::routing::route::RouteFuture<hyper::body::body::Body,enum2$<core::convert::Infallible> >,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> > 
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tower-0.4.13\src\macros.rs:38
  50: core::future::future::impl$1::poll<alloc::boxed::Box<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >,enum2$
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\future.rs:124
  51: tower::util::oneshot::impl$3::poll<tower::util::boxed_clone::BoxCloneService<http::request::Request<hyper::body::body::Body>,http::response::Response<http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >,enum2$<cor
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tower-0.4.13\src\util\oneshot.rs:97
  52: axum::routing::route::impl$5::poll<hyper::body::body::Body,enum2$<core::convert::Infallible> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\axum-0.6.0-rc.4\src\routing\route.rs:144
  53: hyper::proto::h1::dispatch::impl$6::poll_msg<axum::routing::service::RouterService<hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:491
  54: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<axum::routing::service::RouterService<hyper::body::body::Body>,hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:297
  55: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<axum::routing::service::RouterService<hyper::body::body::Body>,hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:161
  56: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<axum::routing::service::RouterService<hyper::body::body::Body>,hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:137
  57: hyper::proto::h1::dispatch::Dispatcher<hyper::proto::h1::dispatch::Server<axum::routing::service::RouterService<hyper::body::body::Body>,hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:120
  58: hyper::proto::h1::dispatch::impl$1::poll<hyper::proto::h1::dispatch::Server<axum::routing::service::RouterService<hyper::body::body::Body>,hyper::body::body::Body>,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\proto\h1\dispatch.rs:424
  59: hyper::server::conn::impl$6::poll<hyper::server::tcp::addr_stream::AddrStream,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,axum::routing::service::RouterService<hyper::body::body::Body>,enum2$<hyper::common:
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\server\conn.rs:952
  60: hyper::server::conn::upgrades::impl$1::poll<hyper::server::tcp::addr_stream::AddrStream,http_body::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes,axum_core::error::Error>,axum::routing::service::RouterService<hyper::body::body::Body>,enum2$<hype
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\server\conn.rs:1012
  61: hyper::server::server::new_svc::impl$1::poll<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum::routing::service::RouterService<hyper::
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.14.23\src\server\server.rs:741
  62: tokio::runtime::task::core::impl$3::poll::closure$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Bod
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\core.rs:184
  63: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::Route
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\loom\std\unsafe_cell.rs:14
  64: tokio::runtime::task::core::CoreStage<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum::rou
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\core.rs:174
  65: tokio::runtime::task::harness::poll_future::closure$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::B
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\harness.rs:480
  66: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_ma
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\panic\unwind_safe.rs:271
  67: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::Into
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panicking.rs:492
  68: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$1::complete::closure_env$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service
  69: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panicking.rs:456
  70: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMake
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panic.rs:137
  71: tokio::runtime::task::harness::poll_future<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\harness.rs:468
  72: tokio::runtime::task::harness::Harness<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum::ro
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\harness.rs:104
  73: tokio::runtime::task::harness::Harness<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum::ro
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\harness.rs:57
  74: tokio::runtime::task::raw::poll<hyper::server::server::new_svc::NewSvcTask<hyper::server::tcp::addr_stream::AddrStream,axum::routing::into_make_service::IntoMakeServiceFuture<axum::routing::service::RouterService<hyper::body::body::Body> >,axum::routing::
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\raw.rs:194
  75: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\raw.rs:134
  76: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::worker::Shared> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::worker::Shared> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\task\mod.rs:385
  77: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\scheduler\multi_thread\worker.rs:421
  78: tokio::coop::with_budget::closure$0<enum2$<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core,alloc::alloc::Global>,tuple$<> > >,tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure_env$0>
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\coop.rs:102
  79: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::try_with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum2$<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Cor
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:445
  80: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget> >::with<core::cell::Cell<tokio::coop::Budget>,tokio::coop::with_budget::closure_env$0<enum2$<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core,al
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:421
  81: tokio::coop::with_budget
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\coop.rs:95
  82: tokio::coop::budget
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\coop.rs:72
  83: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\scheduler\multi_thread\worker.rs:420
  84: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\scheduler\multi_thread\worker.rs:387
  85: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\scheduler\multi_thread\worker.rs:372
  86: tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::multi_thread::worker::Context>::set<tokio::runtime::scheduler::multi_thread::worker::Context,tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\macros\scoped_tls.rs:61
  87: tokio::runtime::scheduler::multi_thread::worker::run
             at C:\Users\guxin\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.2\src\runtime\scheduler\multi_thread\worker.rs:369
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by zhuxiujia** [comment]
> Intresting, I tried to use the wsl2 to install a utuntu 22.04 in my win11. In the ubuntu I have installed postgress 14.5, and Rust and run the codebase again, this time insert id is still null, but select is ok...
> 
> Ok, I switch back to the win11 but use the postgress 14.5, the result is the same as the above in ubuntu. So the problem is comming from the postgres version.
> 
> so maybe the `last_insert_id` issue can be fixed by a lower version PG. @zhuxiujia do you know which version of PG you support?
> 
> ```
>      Running `target/debug/rbatis_test`
> 2022-11-19 11:55:13.448106587 INFO rbatis::plugin::log - [rbatis] [436494982229135360] Exec   ==> insert into todo_entry (cont,status,deadline,ctime,mtime) VALUES (?,?,?,?,?)
>                                                       [rbatis]                      Args   ==> ["test","Pending",DateTime("2022-11-19 19:55:13.271679603"),DateTime("2022-11-19 19:55:13.271682859"),DateTime("2022-11-19 19:55:13.27168329")]
> insert result: ExecResult { rows_affected: 1, last_insert_id: Null }
> 2022-11-19 11:55:13.472380402 INFO rbatis::plugin::log - [rbatis] [436494982229135360] RowsAffected <== 1
> 2022-11-19 11:55:13.474004885 INFO rbatis::plugin::log - [rbatis] [436494982333992960] Fetch  ==> select * from todo_entry where status = ?
>                                                       [rbatis]                      Args   ==> ["Pending"]
> query result: Ok([TodoEntry { id: Some(1), cont: "test", status: "Pending", deadline: DateTime(2022-11-19 19:55:13.271), ctime: DateTime(2022-11-19 19:55:13.271), mtime: DateTime(2022-11-19 19:55:13.271) }])
> 2022-11-19 11:55:13.484203127 INFO rbatis::plugin::log - [rbatis] [436494982333992960] ReturnRows <== 1
> 2022-11-19 11:55:13.484275074 DEBUG rbatis::decode -     [rbatis] [debug_mode] alloc::vec::Vec<rbatis_test::TodoEntry> => [{"mtime":Timestamp(1668887713271),"ctime":Timestamp(1668887713271),"deadline":Timestamp(1668887713271),"status":"Pending","cont":"test","id":1}]
> ```

pg not support last_insert_id. [see](https://github.com/rbatis/rbatis/blob/master/rbdc-pg/src/connection/mod.rs) on line:266

```rust
return Ok(ExecResult {
                rows_affected: v.rows_affected,
                last_insert_id: Value::Null,
            });
```

If you have a better idea, feel free to submit PR

**Comment by zhuxiujia** [comment]
> 

'the 2.For select statement, the datatime field parse always failed:'

Can you provide the data returned by printing, please enable debug_mode in Cargo.toml

```toml
rbatis = { ......   features = ["debug_mode"]}
```

**Comment by gusvny** [comment]
right, I also check the code and saw that the last_insert_id is not supported in rbdc-pg. 
I saw a solution:
`INSERT INTO persons (lastname,firstname) VALUES ('Smith', 'John') RETURNING id;`
from here https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id

Maybe we can add this ‘RETURNING id’ to the insert statement rbatis generated.

**Comment by Phosphorus-M** [comment]
> right, I also check the code and saw that the last_insert_id is not supported in rbdc-pg. I saw a solution: `INSERT INTO persons (lastname,firstname) VALUES ('Smith', 'John') RETURNING id;` from here [stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id](https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id)
> 
> Maybe we can add this ‘RETURNING id’ to the insert statement rbatis generated.

For this solution, we need to know the name of the field id of any entity, it's complicated, maybe adding an attribute to every entity and then in rbatis adding a flag to check the attribute just in case of being using pg?

**Comment by zhuxiujia** [comment]
last rbatis version,you can use Intercept  RETURNING id;  [see](https://github.com/rbatis/example/blob/main/src/plugin_intercept_returing_id.rs)
