### ISSUE TITLE
發現執行一段時間後會panic， there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by damody** [rbatis/rbatis#85]
遇到一個問題 當掛網接近10小時後，再度使用會突然遇到 Tokio 1.x runtime 跑掉的問題，不知道作者有沒有遇過？

```
[2021-03-16T17:35:06Z INFO  rbatis::plugin::log] [rbatis] [] ReturnRows <== 1
[2021-03-16T17:35:06Z INFO  erps::event_room]  Game id: 1
[2021-03-16T17:35:06Z INFO  erps] server/Game_Pub_5fb1e45/send/login: {"name":"Game_Pub_5fb1e45", "address":"114.32.129.195", "max_server":6, "max_user":12}
[2021-03-16T17:35:06Z INFO  erps] Server Login!
Ok(GameServerLogin(GameServerLoginData { name: "Game_Pub_5fb1e45", address: "114.32.129.195", max_server: 6, max_user: 12 }))
[2021-03-16T17:35:06Z INFO  GameServer::event] login success
[2021-03-17T02:50:27Z INFO  erps] member/Takeshi/send/login: {"id":"Takeshi"}
[2021-03-17T02:50:27Z INFO  rbatis::plugin::log] [rbatis] [] Exec  ==> insert into user (uid, name, honor) values ('Takeshi', 'Takeshi', 0);
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/runtime/context.rs:37:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: tokio::runtime::context::time_handle::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/runtime/context.rs:37:13
   5: std::thread::local::LocalKey<T>::try_with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
   6: std::thread::local::LocalKey<T>::with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
   7: tokio::runtime::context::time_handle
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/runtime/context.rs:35:9
   8: tokio::time::driver::handle::Handle::current
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/driver/handle.rs:49:13
   9: tokio::time::driver::sleep::Sleep::new_timeout
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/driver/sleep.rs:168:22
  10: tokio::time::timeout::timeout
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/timeout.rs:54:27
  11: sqlx_core::pool::inner::SharedPool<DB>::connection::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/inner.rs:239:15
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: sqlx_core::pool::inner::SharedPool<DB>::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/inner.rs:202:23
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: sqlx_core::pool::Pool<DB>::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/mod.rs:252:22
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  17: rbatis_core::db::db_adapter::DBPool::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-core-1.8.79/src/db/db_adapter.rs:221:33
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  19: rbatis::rbatis::Rbatis::exec::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.8.79/src/rbatis.rs:417:28
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  21: erps::event_room::HandleSqlRequest::{{closure}}::{{closure}}
             at ./src/event_room.rs:904:29
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  23: futures_executor::local_pool::block_on::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:23
  24: futures_executor::local_pool::run_executor::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87:37
  25: std::thread::local::LocalKey<T>::try_with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  26: std::thread::local::LocalKey<T>::with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  27: futures_executor::local_pool::run_executor
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83:5
  28: futures_executor::local_pool::block_on
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:5
  29: erps::event_room::HandleSqlRequest::{{closure}}
             at ./src/event_room.rs:889:9
```

**Comment by damody** [comment]
發現只要過一小段時間在一些block_on也能重現
我是直接用 use futures::executor::block_on;
```
block_on(async {
        let sql = format!("update user set online=0 where uid='{}';", data.id);
        CONTEXT.rbatis.exec("", &sql).await;
    });
```
```
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: tokio::runtime::context::time_handle::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/runtime/context.rs:37:13
   5: std::thread::local::LocalKey<T>::try_with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
   6: std::thread::local::LocalKey<T>::with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
   7: tokio::runtime::context::time_handle
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/runtime/context.rs:35:9
   8: tokio::time::driver::handle::Handle::current
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/driver/handle.rs:49:13
   9: tokio::time::driver::sleep::Sleep::new_timeout
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/driver/sleep.rs:168:22
  10: tokio::time::timeout::timeout
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.3.0/src/time/timeout.rs:54:27
  11: sqlx_core::pool::inner::SharedPool<DB>::connection::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/inner.rs:239:15
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: sqlx_core::pool::inner::SharedPool<DB>::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/inner.rs:202:23
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: sqlx_core::pool::Pool<DB>::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.5.1/src/pool/mod.rs:252:22
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  17: rbatis_core::db::db_adapter::DBPool::acquire::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-core-1.8.79/src/db/db_adapter.rs:221:33
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  19: rbatis::rbatis::Rbatis::exec::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/rbatis-1.8.79/src/rbatis.rs:417:28
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  21: erps::event_member::logout::{{closure}}
             at ./src/event_member.rs:60:9
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  23: futures_executor::local_pool::block_on::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:23
  24: futures_executor::local_pool::run_executor::{{closure}}
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87:37
  25: std::thread::local::LocalKey<T>::try_with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  26: std::thread::local::LocalKey<T>::with
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  27: futures_executor::local_pool::run_executor
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83:5
  28: futures_executor::local_pool::block_on
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317:5
  29: erps::event_member::logout
             at ./src/event_member.rs:58:5
  30: erps::main::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/main.rs:403:25
  31: erps::main::main::{{closure}}::{{closure}}
             at ./src/main.rs:571:31
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /home/damody/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1335:9
  33: paho_mqtt::async_client::AsyncClient::on_message_arrived
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-0.9.1/src/async_client.rs:329:21
  34: MQTTAsync_deliverMessage
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.5.0/paho.mqtt.c/src/MQTTAsyncUtils.c:2407
  35: Protocol_processPublication
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.5.0/paho.mqtt.c/src/MQTTAsyncUtils.c:2460
  36: MQTTProtocol_handlePublishes
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.5.0/paho.mqtt.c/src/MQTTProtocolClient.c:323
  37: MQTTAsync_cycle
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.5.0/paho.mqtt.c/src/MQTTAsyncUtils.c:2886
  38: MQTTAsync_receiveThread
             at /home/damody/.cargo/registry/src/github.com-1ecc6299db9ec823/paho-mqtt-sys-0.5.0/paho.mqtt.c/src/MQTTAsyncUtils.c:1955
  39: start_thread
  40: __clone
```

**Comment by damody** [comment]
我用跟你 abs_admin的方法做個 CONTEXT.runtime.block_on 就好了，沒事了。

**Comment by zhuxiujia** [comment]
> 我用跟你 abs_admin的方法做個 CONTEXT.runtime.block_on 就好了，沒事了。

完全依賴tokio似乎不是一個明智的選擇，因此新版本還是回歸支持async_std,並且使用async_std提供的features切換tokio 01/02/03或async_std

**Comment by damody** [comment]
請問現在更新 1.8.81之後 use futures::executor::block_on; 可以使用了嗎？

**Comment by zhuxiujia** [comment]
> 請問現在更新 1.8.81之後 use futures::executor::block_on; 可以使用了嗎？

更新到1.8后，建议使用rbatis::core::runtime::task::block_on****

**Comment by damody** [comment]
https://rbatis.github.io/rbatis.io/#/?id=%e6%8f%92%e4%bb%b6%ef%bc%9a%e5%88%86%e5%b8%83%e5%bc%8f%e5%94%af%e4%b8%80id%e9%9b%aa%e8%8a%b1%e7%ae%97%e6%b3%95i64
請大大您的範例也更新一下 感謝~
